FROM ubuntu:18.04
WORKDIR /


ENV FLASK_APP app.py
ENV FLASK_RUN_HOST 0.0.0.0
RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5000
COPY . .
RUN sbt "etl/run" $CAPI
CMD ["sbt", "ui/run"]

## curl -X POST http://localhost:9000/admin/prepare-recipes